services:
  ollama:
    image: ollama/ollama:latest
    networks:
      - llama-net
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - ENV=production
    entrypoint: ["bash", "-c", "apt-get update && apt-get install -y curl && /entrypoint.sh"]
    command: ["ollama"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "5000:8080"
    networks:
      - llama-net
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    entrypoint: ["bash", "-c", "apt-get update && apt-get install -y curl && /entrypoint.sh"]
    command: ["open-webui"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  llama-net:
    driver: bridge